### ISSUE TITLE
.netCore 3

### ISSUE THREAD

**Issue by metheofanis** [ErikEJ/EntityFramework.SqlServerCompact#576]
I don't know if this is the correct place to ask.
It looks like EntityFrameworkCore.SqlServerCompact40.Core is not working for .netCore 3.0.
Is this correct? Any plans to fix it ?
Thanks.

**Comment by ErikEJ** [comment]
This is the correct place, yes.

No current plans, unless a customer will sponsor the effort. Why do you need it? (SQL CE is Windows only)

**Comment by tprodromos** [comment]
I understand.

Well, I need it for a hobby project of mine. Some other libraries suggest using .netcore 3.0.

I guess I'll find another solution.

Thanks.

**Comment by janpavlis** [comment]
Does this mean that there is no plan to support [recently released](https://devblogs.microsoft.com/dotnet/announcing-ef-core-3-0-and-ef-6-3-general-availability/?utm_source=vs_developer_news&utm_medium=referral) **EF Core 3.0**? Since **EF Core 3.0** [targets **.NET Standard 2.1** only](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore/3.0.0?_src=template), which is not implemented by **.NET Framework** (only **.NET Core 3.0** implements it).

**Comment by ErikEJ** [comment]
@janpavlis Yes, that is the current plan. But I think it will be tecnically possible to make the provider run runder .NET Core 3.0 (on Windows desktop only, of course)

**Comment by Monarch73** [comment]
> Why do you need it? (SQL CE is Windows only)

I don't understand your reasoning. SQL CE was Windows only from the beginning. It's nothing really that popped up since .NetCore 3.

I am using SQL CE to develop prototypes and local integration tests and I think it's extremly helpful since it's it provides a great compatibily to sql server. I really appreciate your work you have done so far.

**Comment by ErikEJ** [comment]
>> Why do you need it? (SQL CE is Windows only)

This was just to set expectations - not everyone is be aware of that.

Given that there are 0 upvotes for this issue, it is quite low on my list, and updating the provider for EF Core 5 will be a time consuming undertaking. (Unless someone would want to sponsor that work)

**Comment by Stannieman** [comment]
The question here is not to make it compatible with EF Core, only .NET Core. I'd argue that, since .NET 5 is released now, even skipping 3.1 would be ok. Since almost everything from .NET Framework 4.x is also supported in .NET 3.1/5 I expect it to be just a matter of retargetting the projects.
I have some time beginning next week so I will have a look into it.

One thing this could be really useful for is for migrating old solutions to modern technologies.
In our case we have a .NET Framework 4.x app using EF 6 and SQL Compact.
Currently we can't upgrade to EF Core 3.1/5 because this package only works on the full framework.
On the other hand when we want to migrate to EF Core first we'd like to go directly to the latest EF Core too, which in turn only works on .NET Core (we'll move to a new DB too so no EF Core support needed for this package).
With the latest versions of EF Core and .NET Core being kind of interlocked the only way to really modernize it is to go to both .NET Core and EF Core (+ new DB) in 1 big bang.

Now IF this package would be compatible with .NET 5 then we could first focus on the .NET 5 migration and keep using EF 6 + SQL Compact for a while. Then when that's done we could modernize the DB layer in phase 2.

It has to be said that our app is actually a legacy app that will be EOL not too far in the future, so probably I we won't bother.
But it is a real life example of why one would want EF 6 SQL Compact support on .NET Core.
In case anyone is wondering: the codebase is waaay to large to start a new app from scratch, that would take years.

So to be clear: this is about running this exact same thing on .NET Core 3.1/5 but still for EF 6.
Somehwere next week I'll see if I can get it working.

**Comment by ErikEJ** [comment]
@Stannieman This is not the repository for the EF6 SQL CE provider!

That provider lives in the EF6 repo, https://github.com/dotnet/ef6/tree/master/src/EntityFramework.SqlServerCompact

Probably you could use that provider directly in a .NET Core Windows app

Tips here: https://erikej.github.io/sqlce/2020/08/17/netcore-sql-compact.html

**Comment by Stannieman** [comment]
@ErikEJ oh, wow, perfect.
Thanks!
:D

**Comment by ErikEJ** [comment]
@Stannieman let me know how it goes!
